import Navigation from '@/components/atoms/Navigation/page'
import { ApolloWrapper } from '@/lib/apollo-provider';
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/atoms/Footer/page'

const inter = Inter({ subsets: ['latin'] })
export const revalidate = 5;


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
      <Navigation/>
      <ApolloWrapper>
        {children}
        </ApolloWrapper>
        <Footer/>
        </body>
    </html>
  )
}
