import Navigation from '@/components/Navigation/page'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={inter.className}>
      <Navigation/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
